name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut
      uses: actions/checkout@v2
    - name: Slack Notification on Deploy Start
      id: slack
      uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: |
         {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "GitHubにPushされデプロイが開始されました",
                  "emoji": true
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Repo: ${{ github.event.repository.full_name }}"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "GitHub",
                    "emoji": true
                  },
                  "value": "click_me_123",
                  "url": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                  "action_id": "button-action"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: dx_deploy_id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: |
          Host server
            HostName 118.27.110.225
            User deployer
            Port 546
            IdentityFile ~/.ssh/dx_deploy_id_rsa
    - name: Run Deploy Script
      run: |
        ssh server "cd dx2021-MaterialManagementApp && git pull origin main && docker-compose -f docker-compose.yml build && docker-compose -f docker-compose.yml down && docker-compose -f docker-compose.yml up -d"
    - name: Slack Notification on Deploy End
      id: slack
      uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: |
         {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Deployが終了しました",
                  "emoji": true
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "plain_text",
                  "text": "ビルド結果: ${{ job.status }}",
                  "emoji": true
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}